#ifndef _QwenAttention_h
#define _QwenAttention_h


#include <string>
#include <sstream>
#include "QwenAttention.h"
#include "QwenOperator.h"
#include "common.h"
#include "operators.h"
#include "utils.h"

// buffer to save the KV cache
// (num_layers, 2, num_head * sqlen * head_dim)
// NOTE: The 2, in the second dim, denotes two spaces, where one for storing the current KV-cache, and the other for storing the updated expanded KV cache. 
// NOTE: 1. Lots of memory waste, cf. paged-attention of vLLM.
// TODO: try to only maintain 1 space
static float *** key_states_arr_cache; 
static float *** value_states_arr_cache;
// (num_layers, 1), indicates which space to store the updated KV cache. 
// NOTE that after we store the new KV cache, the KV cache located in the other space expires 
// and then serves as the space to store the next updated cache.
// TODO: try enum try
static int * free_space_indicator; 

// TODO: memory waste check. Add static before void is wrong?
void Qwen3Attention::initialize_memory(const struct qwen3_config config) {
    int max_sqlen = config.max_sqlen;
    int hidden_dim = config.hidden_dim;
    int num_heads = config.num_q_head;
    int num_layers = config.num_layers;

    // allocate_aligned_memory(value_states_transpose_arr, max_sqlen * hidden_dim * sizeof(float));
    free_space_indicator = new int[num_layers];
    for (int i = 0; i < num_layers; i++) free_space_indicator[i] = 0;
    // NOTE: how to allocate memory for float***
    key_states_arr_cache = new float **[num_layers];
    for (int i = 0; i < num_layers; ++i) {
        key_states_arr_cache[i] = new float *[2];
        for (int j = 0; j < 2; ++j) {
            allocate_aligned_memory(key_states_arr_cache[i][j], max_sqlen * hidden_dim * sizeof(float));
        }
    }
    value_states_arr_cache = new float **[num_layers];
    for (int i = 0; i < num_layers; ++i) {
        value_states_arr_cache[i] = new float *[2];
        for (int j = 0; j < 2; ++j) {
            allocate_aligned_memory(value_states_arr_cache[i][j], max_sqlen * hidden_dim * sizeof(float));
        }
    }
}

Qwen3Attention::Qwen3Attention(std::string param_path, const struct qwen3_config config, int layer_idx)
{
    this->layer_idx = layer_idx;
    this->params_path = param_path;
    max_sqlen = config.max_sqlen;
    hidden_dim = config.hidden_dim;
    q_dim = hidden_dim;
    kv_dim = hidden_dim / 4;
    num_q_head = config.num_q_head;
    num_kv_head = config.num_k_head;
    head_dim = q_dim / num_q_head;
    assert (head_dim == kv_dim / num_kv_head);

    IF_DEBUG(
        printf("\e[31m[INFO]\e[m Loading Attention Module\n");
    );
    q_proj = Qwen_Linear_with_bias_Int4(
            param_path + "/q_proj/", 1, q_dim, hidden_dim
    );
    k_proj = Qwen_Linear_with_bias_Int4(
            param_path + "/k_proj/", 1, kv_dim, hidden_dim
    );
    v_proj = Qwen_Linear_with_bias_Int4(
            param_path + "/v_proj/", 1, kv_dim, hidden_dim
        );
    o_proj = Qwen_Linear_with_bias_Int4(
        param_path + "/o_proj/", 1, hidden_dim, hidden_dim
    );
    IF_DEBUG(
        printf("\e[31m[INFO]\e[m Loading Attention qk norm\n");
    );
    q_norm = Qwen3RMSNorm(head_dim);
    q_norm.load((param_path + "/q_norm/weight.bin").c_str());

    k_norm = Qwen3RMSNorm(head_dim);
    k_norm.load((param_path + "/k_norm/weight.bin").c_str());

    // ROPE
    this->rope_embed = RotaryPosEmb(max_sqlen, head_dim, param_path + "/../../../rotary_emb");

    // scaling factor
    float qk_bmm_alpha;
    read_to_array((param_path + "/scaling.bin").c_str(), &qk_bmm_alpha, 1);
    this->qk_bmm = BMM_F32T(qk_bmm_alpha);
    this->pv_bmm = BMM_F32T(1.0f);

}

struct Qwen3Attention_Output Qwen3Attention::forward(struct Qwen3Attention_Input &input)
{
    PROFILE_START(profile_name);
    struct Qwen3Attention_Output output;
    const int sqlen = input.hidden_state.m_dim_y; // the sequence length of tokens generated by last pass or the prefill tokens
    const int bs = input.hidden_state.m_dim_x;
    const int layer_idx = input.layer_idx;
    
    // ---------------------------------------------------------------
    // Stage 1: Generation of Q,K,V
    // ---------------------------------------------------------------
    // TODO: Fused Generation of QKV
    PROFILE_START(profile_name + "::QKV Generation");
    assert (bs == 1);
    Matrix3D<float> query_states_unshape = q_proj.forward(input.hidden_state);
    query_states_unshape.view(bs * sqlen, num_q_head, head_dim);
    Matrix3D<float> query_states_norm = q_norm.forward(query_states_unshape);
    // (bs * sqlen, n_head, head_dim) -> (num_head, bs*sqlen, head_dim)
    Matrix3D<float> query_states = query_states_norm.permute01();
    
    Matrix3D<float> key_states_unshape = k_proj.forward(input.hidden_state);
    key_states_unshape.view(bs * sqlen, num_kv_head, head_dim);
    Matrix3D<float> key_states_norm = k_norm.forward(key_states_unshape);
    Matrix3D<float> key_states = key_states_norm.permute01();
    
    Matrix3D<float> value_states_unshape = v_proj.forward(input.hidden_state);
    value_states_unshape.view(bs * sqlen, num_kv_head, head_dim);
    Matrix3D<float> value_states = value_states_unshape.permute01();
    
    int past_sqlen = 0;
    if (input.has_past_key_value) 
    {
        past_sqlen = input.past_key.m_dim_x;
    }
    int total_context_sqlen = past_sqlen + sqlen;
    this->rope_embed.apply(query_states, key_states, past_sqlen, sqlen);
    PROFILE_END(profile_name + "::QKV Generation");
    
    /*
    TODO: need improvement
    Refresh KV Cache
        KV Cache shape  : ( num_head, past_key_len          , head_dim ) 
        current KV shape: ( num_head, cur_sql               , head_dim ) 
        final KV shape  : ( num_head, past_key_len + cur_sql, head_dim) 
    In this poor implementation, new KV cache space is managed by copying original KV cache and current KV value.
    Why do we do this? The reason is that the old KV cache takes up a chunk of contiguous space, we need a new space
    when append new elements along the second dimension.
    free_space_indicator identifies new and old KV cache space.
    */
    PROFILE_START(profile_name + "::refresh KV Cache");
    Matrix3D<float> entire_value_states;
    Matrix3D<float> entire_key_states;
    // Matrix3D<float> final_value_states(all_value_state_arr, num_kv_head, total_context_sqlen, head_dim);
    // Matrix3D<float> final_key_states(all_key_state_arr, num_kv_head, total_context_sqlen, head_dim);
    if (!input.has_past_key_value)
    {
        // num_kv_head, bs * first_round_prompt_sqlen, head_dim
        entire_key_states = key_states.permute01();
        entire_value_states = value_states_unshape;
    }
    else 
    {
        /* 
        key_states_unshape: (cur_len, num_kv_head, head_dim);
        k_cache shape: (past_sqlen, num_k_heads, head_dim)

        */
        // TODO: Does copy occur? Consider use std::move
        Matrix3D<float> k_cache = input.past_key;
        Matrix3D<float> v_cache = input.past_value;
        // assert(k_cache.m_dim_x == max_sqlen);
        assert(k_cache.m_dim_y == num_kv_head);
        assert(k_cache.m_dim_z == head_dim);
        entire_key_states = (k_cache.cat(key_states.permute01()));
        entire_value_states = (v_cache.cat(value_states_unshape));
    
    }


    int group_size = num_q_head / num_kv_head;
    Matrix3D<float> final_key_states_expanded = entire_key_states.permute01().repeat(0, group_size);
    Matrix3D<float> final_value_states_expanded = entire_value_states.permute01().repeat(0, group_size);

    PROFILE_END(profile_name + "::refresh KV Cache");

    // ---------------------------------------------------------------
    // Stage 2: Attention Computation
    // ---------------------------------------------------------------
    PROFILE_START(profile_name + "::self-attention");
    // step1: get attention weight
    Matrix3D<float>  attn_weights(num_q_head, sqlen, total_context_sqlen); // shape: (sqlen, final_sqlen)
    // (num_head, sqlen, head_dim) x (num_head, final_sqlen, head_dim) -> (num_head, sqlen, final_sqlen)
    this->qk_bmm.forward(query_states, final_key_states_expanded, attn_weights);
    assert(not has_nan(attn_weights));
    IF_DEBUG_ATTENTION(        
        query_states.statistics();
        final_key_states_expanded.statistics();
        attn_weights.statistics();
    );
    // step2: apply causal mask
    batch_Add(attn_weights, input.attention_mask, attn_weights);
    assert(not has_nan(attn_weights));
    for (int i = 0; i < attn_weights.length(); i++)
    {
        if (std::isinf(attn_weights.data()[i]))
        {
            attn_weights.data()[i] = std::numeric_limits<float>::lowest();
        }
    }
    assert(not has_nan(attn_weights));
    // step3: apply softmax
    Matrix3D<float> attn_probs(num_q_head, sqlen, total_context_sqlen);
    // TODO: check the softmax implementation. Why find the max value?
    softmax(attn_weights, attn_probs, 2);
    
    assert(not has_nan(attn_probs));

    // step4: get output
    Matrix3D<float> attn_output( num_q_head, bs * sqlen, head_dim);
    // TODO: there is a legacy implementation, need to check
    this->pv_bmm.forward_weight_untransposed(attn_probs, final_value_states_expanded, attn_output);
    // step5: reshape output: (num_head, sqlen, head_dim) -> (1, sqlen, sqlen * head_dim)
    Matrix3D<float> attn_reshape = attn_output.permute01();
    attn_reshape.view(bs, sqlen, hidden_dim);
    // step6: output projection
    Matrix3D<float> attn_output_fp = this->o_proj.forward(attn_reshape);
    PROFILE_END(profile_name + "::self-attention");
    // --------------------------------------------------------------
    // Debug
    // --------------------------------------------------------------

    IF_DEBUG_ATTENTION(([&] {
        // only account for prompt stage correctness
        std::string save_dir = params_path + "/activation/";
        std::vector<std::pair<Matrix3D<float>, std::string>> state_dict{
            {query_states, "query_states-gt.bin"},
            {key_states, "key_states-gt.bin"},
            {value_states, "value_states-gt.bin"},
            {final_value_states_expanded, "final_value_states_expanded-gt.bin"},
            {final_key_states_expanded, "final_key_states_expanded-gt.bin"},
            {attn_weights, "attn_weights-gt.bin"},
            {attn_output_fp, "attn_output_fp-gt.bin"}
        };
        for (auto& [matrix, name] : state_dict) {
            assert(matrix.compare_with_gt(save_dir + name));
        }
        query_states.statistics();
        key_states.statistics();
        value_states.statistics();
        attn_output.statistics();
        attn_output_fp.statistics();
    }())
    );

    IF_DEBUG_IO(

        std::ostringstream oss;
        std::string save_path;
        // input
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/input.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), input.hidden_state.m_data, input.hidden_state.length());
        // q,k,v
        oss.str("");
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/q.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), query_states_unshape.m_data, query_states_unshape.length());
        oss.str("");
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/k.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), key_states_unshape.m_data, key_states_unshape.length());
        oss.str("");
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/v.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), value_states_unshape.m_data, value_states_unshape.length());

        // q,k fed with rope
        oss.str(""); 
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/q_with_rope.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), query_states.m_data, query_states.length());
        oss.str(""); 
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/k_with_rope.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), key_states.m_data, key_states.length());
        
        // final q,k,v
        oss.str(""); 
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/final_q.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), query_states.m_data, query_states.length());
        oss.str(""); 
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/final_k.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), final_key_states.m_data, final_key_states.length());
        oss.str(""); 
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/final_v.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), final_value_states.m_data, final_value_states.length());

        // attention output before out_proj
        oss.str("");
        oss << "/root/workspace/tinyml/TinyChatEngine/qwen-7b-chat/transformer/layer" << input.layer_idx << 
            "/self_attn/activation/attn_before_out.bin";
        save_path = oss.str();
        write_array_to_file(save_path.c_str(), attn_reshape.m_data, attn_reshape.length());
    );
    

    // ---------------------------------------------------------------
    // stage3: Output assignment and wrapping up instrumentation code
    // ---------------------------------------------------------------
    output.attn_output = attn_output_fp;
    output.past_key_value = { entire_key_states, entire_value_states };
    PROFILE_END(profile_name);
    return output;
}

#endif