#ifndef _QwenAttention_h
#define _QwenAttention_h


#include <string>
#include <sstream>
#include <type_traits>
#include <vector>
#include "QwenAttention.h"
#include "QwenOperator.h"
#include "common.h"
#include "operators.h"
#include "utils.h"


Qwen3Attention::Qwen3Attention(float * k_cache_space_, float * v_cache_space_, std::string param_path, struct qwen3_config config, int layer_idx)
{
    k_cache_space = k_cache_space_;
    v_cache_space = v_cache_space_;
    this->layer_idx = layer_idx;
    this->params_path = param_path;
    max_sqlen = config.max_sqlen;
    hidden_dim = config.hidden_dim;
    q_dim = hidden_dim;
    kv_dim = hidden_dim / 4;
    num_q_head = config.num_q_head;
    num_kv_head = config.num_kv_head;
    head_dim = q_dim / num_q_head;
    assert (head_dim == kv_dim / num_kv_head);

    IF_DEBUG(
        printf("\e[31m[INFO]\e[m Loading Attention Module\n");
    );
    q_proj = Qwen_Linear_with_bias_Int4(
            param_path + "/q_proj/", 1, q_dim, hidden_dim
    );
    k_proj = Qwen_Linear_with_bias_Int4(
            param_path + "/k_proj/", 1, kv_dim, hidden_dim
    );
    v_proj = Qwen_Linear_with_bias_Int4(
            param_path + "/v_proj/", 1, kv_dim, hidden_dim
        );
    o_proj = Qwen_Linear_with_bias_Int4(
        param_path + "/o_proj/", 1, hidden_dim, hidden_dim
    );
    IF_DEBUG(
        printf("\e[31m[INFO]\e[m Loading Attention qk norm\n");
    );
    q_norm = Qwen3RMSNorm(head_dim);
    q_norm.load((param_path + "/q_norm/weight.bin").c_str());

    k_norm = Qwen3RMSNorm(head_dim);
    k_norm.load((param_path + "/k_norm/weight.bin").c_str());

    // ROPE
    this->rope_embed = RotaryPosEmb(max_sqlen, head_dim, param_path + "/../../../rotary_emb");

    // scaling factor
    float qk_bmm_alpha;
    read_to_array((param_path + "/scaling.bin").c_str(), &qk_bmm_alpha, 1);
    this->qk_bmm = bgemmGQA(qk_bmm_alpha, num_q_head, num_kv_head);
    this->pv_bmm = bgemmGQA(1.0f, num_q_head, num_kv_head);

}



struct Qwen3Attention_Output Qwen3Attention::forward(struct Qwen3Attention_Input &input)
{
    const int sqlen = input.hidden_state.m_dim_y; // the sequence length of tokens generated by last pass or the prefill tokens
    int past_sqlen = input.past_sqlen;
    int total_context_sqlen = past_sqlen + sqlen;
    

    struct Qwen3Attention_Output output;
    const int bs = input.hidden_state.m_dim_x;
    const int layer_idx = input.layer_idx;
    if (sqlen > 1)
    {
        forward_profile_name = "[ P Stage ]: " + profile_name;
    }
    else {
        forward_profile_name = "[ AG Stage ]: " + profile_name;

    }

    PROFILE_START(forward_profile_name);
    
    // ---------------------------------------------------------------
    // Stage 1: Generation of Q,K,V
    // ---------------------------------------------------------------
    // TODO: Fused Generation of QKV
    PROFILE_START(forward_profile_name + "::QKV Generation");
    assert (bs == 1);
    Matrix3D<float> query_states_unshape = q_proj.forward(input.hidden_state);
    query_states_unshape.view(bs * sqlen, num_q_head, head_dim);
    Matrix3D<float> query_states_norm = q_norm.forward(query_states_unshape);
    // (bs * sqlen, n_head, head_dim) -> (num_head, bs*sqlen, head_dim)
    Matrix3D<float> query_states = query_states_norm.permute01();
    
    Matrix3D<float> key_states_unshape = k_proj.forward(input.hidden_state);
    key_states_unshape.view(bs * sqlen, num_kv_head, head_dim);
    Matrix3D<float> key_states_norm = k_norm.forward(key_states_unshape);
    Matrix3D<float> key_states = key_states_norm.permute01();
    
    Matrix3D<float> value_states_unshape = v_proj.forward(input.hidden_state);
    value_states_unshape.view(bs * sqlen, num_kv_head, head_dim);
    Matrix3D<float> value_states = value_states_unshape.permute01();
    
    this->rope_embed.apply(query_states, key_states, past_sqlen, sqlen);
    PROFILE_END(forward_profile_name + "::QKV Generation");
    

    /* ---------------------------------------------------------------
    Stage 2: Refresh KV Cache
    KV Cache shape  : ( num_head, past_key_len          , head_dim ) 
    current KV shape: ( num_head, cur_sql               , head_dim ) 
    final KV shape  : ( num_head, past_key_len + cur_sql, head_dim ) 
    --------------------------------------------------------------- */
    PROFILE_START(forward_profile_name + "::refresh KV Cache");
    PROFILE_START(forward_profile_name + "::refresh KV Cache :: concat old and new");
    // copy new kv into cache
    float * new_k_states_ptr = key_states.data();
    float * new_v_states_ptr = value_states.data();
    float * first_head_k_cache_end = k_cache_space + past_sqlen * head_dim;
    float * first_head_v_cache_end = v_cache_space + past_sqlen * head_dim;
    float * past_k_cache_end = first_head_k_cache_end;
    float * past_v_cache_end = first_head_v_cache_end;
    int new_head_stride = sqlen * head_dim;             // the stride (in elements) between two heads in new KV
    int context_head_stride = max_sqlen * head_dim;     // the stride (in elements) between two heads in KV Cache
    for (int head_idx = 0; head_idx < num_kv_head; head_idx++)
    {
        std::copy(new_k_states_ptr, new_k_states_ptr + new_head_stride, past_k_cache_end);
        std::copy(new_v_states_ptr, new_v_states_ptr + new_head_stride, past_v_cache_end);
        new_k_states_ptr += new_head_stride;
        new_v_states_ptr += new_head_stride;
        past_k_cache_end += context_head_stride;
        past_v_cache_end += context_head_stride;
    }
    PROFILE_END(forward_profile_name + "::refresh KV Cache :: concat old and new");

    MatrixView<float> k_cache_view = MatrixView<float>(
        k_cache_space,
        num_kv_head,
        total_context_sqlen,
        head_dim,
        // NOTE the stride here
        context_head_stride,
        head_dim,
        1
    );

    MatrixView<float> v_cache_view = MatrixView<float>(
        v_cache_space,
        num_kv_head,
        total_context_sqlen,
        head_dim,
        // NOTE the stride here
        context_head_stride,
        head_dim,
        1
    );
    int group_size = num_q_head / num_kv_head;
    MatrixView<float> k_cache_expanded_view = k_cache_view.repeat_dimension(0, group_size);
    MatrixView<float> v_cache_expanded_view = v_cache_view.repeat_dimension(0, group_size);
    // PROFILE_START(forward_profile_name + "::refresh KV Cache :: permute");
    // Matrix3D<float> final_key_states_expanded = entire_key_states.permute01();
    // Matrix3D<float> final_value_states_expanded = entire_value_states.permute01();
    // PROFILE_END(forward_profile_name + "::refresh KV Cache :: permute");
    // PROFILE_START(forward_profile_name + "::refresh KV Cache :: repeat");
    // final_key_states_expanded = final_key_states_expanded.repeat(0, group_size);
    // final_value_states_expanded = final_value_states_expanded.repeat(0, group_size);
    // PROFILE_END(forward_profile_name + "::refresh KV Cache :: repeat");

    PROFILE_END(forward_profile_name + "::refresh KV Cache");

    // ---------------------------------------------------------------
    // Stage 2: Attention Computation
    // ---------------------------------------------------------------
    PROFILE_START(forward_profile_name + "::self-attention");
    // step1: get attention weight
    Matrix3D<float>  attn_weights(num_q_head, sqlen, total_context_sqlen); // shape: (sqlen, final_sqlen)
    // (num_head, sqlen, head_dim) x (num_head, final_sqlen, head_dim) -> (num_head, sqlen, final_sqlen)
    PROFILE_START(forward_profile_name + "::self-attention :: qk_bmm");
    // this->qk_bmm.forward(query_states, k_cache_view, attn_weights);
    this->qk_bmm.forward_openblas_qk(query_states, k_cache_view, attn_weights);
    PROFILE_END(forward_profile_name + "::self-attention :: qk_bmm");
    PROFILE_START(forward_profile_name + "::self-attention :: batch_add");
    assert(not has_nan(attn_weights));
    // step2: apply causal mask
    batch_Add(attn_weights, input.attention_mask, attn_weights);
    assert(not has_nan(attn_weights));
    for (int i = 0; i < attn_weights.length(); i++)
    {
        if (std::isinf(attn_weights.data()[i]))
        {
            attn_weights.data()[i] = std::numeric_limits<float>::lowest();
        }
    }
    assert(not has_nan(attn_weights));
    PROFILE_END(forward_profile_name + "::self-attention :: batch_add");
    // step3: apply softmax
    Matrix3D<float> attn_probs(num_q_head, sqlen, total_context_sqlen);
    // TODO: check the softmax implementation. Why find the max value?
    PROFILE_START(forward_profile_name + "::self-attention :: softmax");
    softmax(attn_weights, attn_probs, 2);
    PROFILE_END(forward_profile_name + "::self-attention :: softmax");
    
    assert(not has_nan(attn_probs));

    // step4: get output
    PROFILE_START(forward_profile_name + "::self-attention :: pv_bmm");
    Matrix3D<float> attn_output( num_q_head, bs * sqlen, head_dim);
    // TODO: there is a legacy implementation, need to check
    // this->pv_bmm.forward_weight_untransposed(attn_probs, v_cache_view, attn_output);
    this->pv_bmm.forward_openblas_pv(attn_probs, v_cache_view, attn_output);
    PROFILE_END(forward_profile_name + "::self-attention :: pv_bmm");
    // step5: reshape output: (num_head, sqlen, head_dim) -> (1, sqlen, sqlen * head_dim)
    Matrix3D<float> attn_reshape = attn_output.permute01();
    attn_reshape.view(bs, sqlen, hidden_dim);
    // step6: output projection
    PROFILE_START(forward_profile_name + "::self-attention :: output_proj");
    Matrix3D<float> attn_output_fp = this->o_proj.forward(attn_reshape);
    PROFILE_END(forward_profile_name + "::self-attention :: output_proj");
    PROFILE_END(forward_profile_name + "::self-attention");
    // --------------------------------------------------------------
    // Debug
    // --------------------------------------------------------------
    IF_DEBUG_ATTENTION(([&] {
        printf("k cache statrt %p; first value = %f\n", k_cache_space, *k_cache_space);
        Matrix3D<float> final_key_states_expanded = k_cache_expanded_view.contiguous();
        std::string save_dir = params_path + "/activation/" + std::to_string(past_sqlen) + "/";
        std::vector<std::pair<Matrix3D<float>, std::string>> state_dict{
            {query_states, "query_states-gt.bin"},
            {key_states, "key_states-gt.bin"},
            {value_states, "value_states-gt.bin"},
            {final_key_states_expanded, "final_key_states_expanded-gt.bin"},
            // {final_value_states_expanded, "final_value_states_expanded-gt.bin"},
            {attn_weights, "attn_weights-gt.bin"},
            {attn_output_fp, "attn_output_fp-gt.bin"}
        };
        for (auto& [matrix, name] : state_dict) {
            printf("Evaluating %s ... ", name.c_str());
            assert(matrix.compare_with_gt(save_dir + name));
            printf(" matched\n");

        }
        query_states.statistics();
        key_states.statistics();
        value_states.statistics();
        attn_output.statistics();
        attn_output_fp.statistics();
    }());
    );
    // ---------------------------------------------------------------
    // stage3: Output assignment and wrapping up instrumentation code
    // ---------------------------------------------------------------
    output.attn_output = attn_output_fp;
    PROFILE_END(forward_profile_name);
    return output;
}

#endif