#ifndef _QwenAttention_h
#define _QwenAttention_h


#include <string>
#include "QwenAttention.h"
#include "QwenOperator.h"
#include "common.h"
#include "operators.h"
#include "utils.h"


Qwen3Attention::Qwen3Attention(ModelContext *ctx, float * k_cache_space_, float * v_cache_space_, std::string param_path, struct qwen3_config config, int layer_idx)
    : context_(ctx)
    , k_cache_space(k_cache_space_)
    , v_cache_space(v_cache_space_)
    , layer_idx(layer_idx)
    , params_path(param_path)
    , max_sqlen(config.max_sqlen)
    , hidden_dim(config.hidden_dim)
    , q_dim(hidden_dim)
    , kv_dim(hidden_dim / 4)
    , num_q_head(config.num_q_head)
    , num_kv_head(config.num_kv_head)
    , head_dim(config.head_dim)
    , q_norm(head_dim)
    , k_norm(head_dim)
    , rope_embed(max_sqlen, head_dim, param_path + "/../../../rotary_emb")
    , qkv_proj(ctx, param_path + "/qkv_proj/", 1, q_dim + 2 * kv_dim, hidden_dim)
    , o_proj(ctx, param_path + "/o_proj/", 1, hidden_dim, hidden_dim)
{
    assert (head_dim == kv_dim / num_kv_head);

    IF_DEBUG( printf("\e[31m[INFO]\e[m Loading Attention Module\n"););
    IF_DEBUG( printf("\e[31m[INFO]\e[m Attention Module Loaded\n"););
    IF_DEBUG( printf("\e[31m[INFO]\e[m Loading Attention qk norm\n"););
    
    q_norm.load((param_path + "/q_norm/weight.bin").c_str());
    k_norm.load((param_path + "/k_norm/weight.bin").c_str());
    
    IF_DEBUG( printf("\e[31m[INFO]\e[m Attention qk norm Loaded\n"););

    // scaling factor
    float qk_bmm_alpha;
    read_to_array((param_path + "/scaling.bin").c_str(), &qk_bmm_alpha, 1);
    this->qk_bmm = bgemxGQA(qk_bmm_alpha, num_q_head, num_kv_head);
    this->pv_bmm = bgemxGQA(1.0f, num_q_head, num_kv_head);
}



struct Qwen3Attention_Output Qwen3Attention::forward(struct Qwen3Attention_Input &input)
{
    const int sqlen = input.hidden_state->m_dim_y; // the sequence length of tokens generated by last pass or the prefill tokens
    int past_sqlen = input.past_sqlen;
    int total_context_sqlen = past_sqlen + sqlen;
    

    const int bs = input.hidden_state->m_dim_x;
    const int layer_idx = input.layer_idx;
    if (sqlen > 1)
    {
        forward_profile_name = "[ P Stage ]: " + profile_name;
    }
    else {
        forward_profile_name = "[ AG Stage ]: " + profile_name;

    }

    PROFILE_START(forward_profile_name);
    
    // ---------------------------------------------------------------
    // Stage 1: Generation of Q,K,V
    // ---------------------------------------------------------------
    // Fused Generation of QKV
    PROFILE_START(forward_profile_name + "::QKV Generation");
    assert (bs == 1);
    Matrix3D<float> qkv = qkv_proj.forward(*input.hidden_state);
    // TODO: Implement or use a slice method for Matrix3D to split qkv into q, k, v
    // Example assumes qkv is (bs*sqlen, q_dim + 2*kv_dim)
    Matrix3D<float> query_states_unshape = qkv.slice(0, q_dim); // (bs*sqlen, num_q_head, head_dim)
    Matrix3D<float> key_states_unshape   = qkv.slice(q_dim, q_dim + kv_dim); // (bs*sqlen, num_kv_head, head_dim)
    Matrix3D<float> value_states_unshape = qkv.slice(q_dim + kv_dim, q_dim + 2*kv_dim); // (bs*sqlen, num_kv_head, head_dim)
    query_states_unshape.view(bs * sqlen, num_q_head, head_dim);
    Matrix3D<float> query_states_norm = q_norm.forward(query_states_unshape);
    Matrix3D<float> query_states = query_states_norm.permute01();
    key_states_unshape.view(bs * sqlen, num_kv_head, head_dim);
    Matrix3D<float> key_states_norm = k_norm.forward(key_states_unshape);
    Matrix3D<float> key_states = key_states_norm.permute01();
    value_states_unshape.view(bs * sqlen, num_kv_head, head_dim);
    Matrix3D<float> value_states = value_states_unshape.permute01();
    this->rope_embed.apply(query_states, key_states, past_sqlen, sqlen);
    PROFILE_END(forward_profile_name + "::QKV Generation");
    

    /* ---------------------------------------------------------------
    Stage 2: Refresh KV Cache
    KV Cache shape  : ( num_head, past_key_len          , head_dim ) 
    current KV shape: ( num_head, cur_sql               , head_dim ) 
    final KV shape  : ( num_head, past_key_len + cur_sql, head_dim ) 
    --------------------------------------------------------------- */
    PROFILE_START(forward_profile_name + "::refresh KV Cache");
    PROFILE_START(forward_profile_name + "::refresh KV Cache :: concat old and new");
    // copy new kv into cache
    float * new_k_states_ptr = key_states.data();
    float * new_v_states_ptr = value_states.data();
    float * first_head_k_cache_end = k_cache_space + past_sqlen * head_dim;
    float * first_head_v_cache_end = v_cache_space + past_sqlen * head_dim;
    float * past_k_cache_end = first_head_k_cache_end;
    float * past_v_cache_end = first_head_v_cache_end;
    int new_head_stride = sqlen * head_dim;             // the stride (in elements) between two heads in new KV
    int context_head_stride = max_sqlen * head_dim;     // the stride (in elements) between two heads in KV Cache
    for (int head_idx = 0; head_idx < num_kv_head; head_idx++)
    {
        std::copy(new_k_states_ptr, new_k_states_ptr + new_head_stride, past_k_cache_end);
        std::copy(new_v_states_ptr, new_v_states_ptr + new_head_stride, past_v_cache_end);
        new_k_states_ptr += new_head_stride;
        new_v_states_ptr += new_head_stride;
        past_k_cache_end += context_head_stride;
        past_v_cache_end += context_head_stride;
    }
    PROFILE_END(forward_profile_name + "::refresh KV Cache :: concat old and new");

    MatrixView<float> k_cache_view (
        k_cache_space,
        num_kv_head,
        total_context_sqlen,
        head_dim,
        // NOTE the stride here
        context_head_stride,
        head_dim,
        1
    );

    MatrixView<float> v_cache_view(
        v_cache_space,
        num_kv_head,
        total_context_sqlen,
        head_dim,
        // NOTE the stride here
        context_head_stride,
        head_dim,
        1
    );
    int group_size = num_q_head / num_kv_head;

    PROFILE_END(forward_profile_name + "::refresh KV Cache");

    // ---------------------------------------------------------------
    // Stage 2: Attention Computation
    // ---------------------------------------------------------------
    PROFILE_START(forward_profile_name + "::self-attention");
    // step1: get attention weight
    Matrix3D<float>  attn_weights(num_q_head, sqlen, total_context_sqlen); // shape: (sqlen, final_sqlen)
    // (num_head, sqlen, head_dim) x (num_head, final_sqlen, head_dim) -> (num_head, sqlen, final_sqlen)
    PROFILE_START(forward_profile_name + "::self-attention :: qk_bmm");
    // this->qk_bmm.forward(query_states, k_cache_view, attn_weights);
    // this->qk_bmm.forward_openblas_qk(query_states, k_cache_view, attn_weights);
    this->qk_bmm.forward_ink_kernel_qk(query_states, k_cache_view, attn_weights);
    PROFILE_END(forward_profile_name + "::self-attention :: qk_bmm");
    PROFILE_START(forward_profile_name + "::self-attention :: batch_add");
    assert(not has_nan(attn_weights));
    // step2: apply causal mask
    batch_Add(attn_weights, *input.attention_mask, attn_weights);
    assert(not has_nan(attn_weights));
    for (int i = 0; i < attn_weights.length(); i++)
    {
        if (std::isinf(attn_weights.data()[i]))
        {
            attn_weights.data()[i] = std::numeric_limits<float>::lowest();
        }
    }
    assert(not has_nan(attn_weights));
    PROFILE_END(forward_profile_name + "::self-attention :: batch_add");
    // step3: apply softmax
    Matrix3D<float> attn_probs(num_q_head, sqlen, total_context_sqlen);
    // TODO: check the softmax implementation. Why find the max value?
    PROFILE_START(forward_profile_name + "::self-attention :: softmax");
    softmax(attn_weights, attn_probs);
    PROFILE_END(forward_profile_name + "::self-attention :: softmax");
    
    assert(not has_nan(attn_probs));

    // step4: get output
    PROFILE_START(forward_profile_name + "::self-attention :: pv_bmm");
    Matrix3D<float> attn_output( num_q_head, bs * sqlen, head_dim);
    // TODO: there is a legacy implementation, need to check
    // this->pv_bmm.forward_weight_untransposed(attn_probs, v_cache_view, attn_output);
    // this->pv_bmm.forward_openblas_pv(attn_probs, v_cache_view, attn_output);
    this->pv_bmm.forward_ink_kernel_pv(attn_probs, v_cache_view, attn_output);
    // this->pv_bmm.forward_mix_kernel_pv(attn_probs, v_cache_view, attn_output);
    PROFILE_END(forward_profile_name + "::self-attention :: pv_bmm");
    // step5: reshape output: (num_head, sqlen, head_dim) -> (1, sqlen, sqlen * head_dim)
    Matrix3D<float> attn_reshape = attn_output.permute01();
    attn_reshape.view(bs, sqlen, hidden_dim);
    // step6: output projection
    PROFILE_START(forward_profile_name + "::self-attention :: output_proj");
    Matrix3D<float> attn_output_fp = this->o_proj.forward(attn_reshape);
    PROFILE_END(forward_profile_name + "::self-attention :: output_proj");
    PROFILE_END(forward_profile_name + "::self-attention");
    // ---------------------------------------------------------------
    // stage3: Output assignment and wrapping up instrumentation code
    // ---------------------------------------------------------------
    struct Qwen3Attention_Output output(std::move(attn_output_fp));
    PROFILE_END(forward_profile_name);
    return output;
}

#endif